version: "3.8"

services:

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  mysqldb:
    image: mariadb:10.4.21
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=flightadvisor
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
      cache:
        condition: service_started
    build: ./
    restart: on-failure
    ports:
      - "6868:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/flightadvisor?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect",
        "flightadvisor.app.jwtCookieName": "flightadvisor-jwt",
        "flightadvisor.app.jwtSecret": "3I70uAdMQq5yIl4FeBvjV9faL0PKpxeE",
        "flightadvisor.app.jwtExpirationMs": "86400000",
        "spring.servlet.multipart.max-file-size": "10MB",
        "spring.servlet.multipart.max-request-size": "10MB",
        "spring.redis.host": "cache",
        "spring.redis.port": "6379",
        "spring.redis.password": "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  cache:
    driver: local